apiVersion: v2
name: confidential-containers
description: Helm chart for Confidential Containers deployment
type: application
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: "0.21.0"
# This is the version number of the application being deployed.
appVersion: "0.21.0"
maintainers:
  - name: Confidential Containers Community
    url: https://github.com/confidential-containers
# Dependencies
dependencies:
  - name: kata-deploy
    alias: kata-as-coco-runtime
    version: "4.0.0"
    repository: "oci://ghcr.io/kata-containers/kata-deploy-charts"
    condition: kata-as-coco-runtime.enabled
  - name: peerpods
    version: "0.4.0"
    repository: "oci://ghcr.io/confidential-containers/cloud-api-adaptor/charts"
    condition: peerpods.enabled
